site_name: Micro-Loan Eligibility App
theme:
  name: material
  palette:
    scheme: default  # Light mode; use 'slate' for dark mode
    primary: green   # Primary color
    accent: light green  # Accent color

nav:
  - Home: index.md
  - Setup: setup.md
  - Usage: usage.md
  - Team: team.md
